/* This file was generated by syncqt. */
#ifndef QT_QT3DQUICK_VERSION_H
#define QT_QT3DQUICK_VERSION_H

#define QT3DQUICK_VERSION_STR "6.5.2"

#define QT3DQUICK_VERSION 0x060502

#endif // QT_QT3DQUICK_VERSION_H
